### PR TITLE
chore(deprecations): import `reads` from '@ember/object/computed'

### PR DESCRIPTION
**Pull request by gilest**
## Description

Resolves deprecation id: [deprecated-run-loop-and-computed-dot-access](https://deprecations.emberjs.com/v3.x/#toc_deprecated-run-loop-and-computed-dot-access)

### Bug Fix

- [x] All existing unit tests are still passing (if applicable)
- [ ] Add new passing unit tests to cover the code introduced by your PR
- [ ] Update the readme
- [ ] Update or add any necessary API documentation
- [ ] Add some [steps](#steps-to-test) so we can test your bug fix
- [x] The PR title is in the [conventional commit](#conventional-commit-spec) format: e.g. `fix(<area>): fixed bug #issue-number`
- [ ] Add your info to the [contributors](#packagejson-contributors) array in package.json!

## Steps to Test

Just a deprecation change. 😅  this is an intense PR template...

### CODE REVIEW

**Comment by gilest** [comment]
@sherwinski @frederickfogerty could we take a look at this please?

This deprecated usage is a blocker for addon consumers wanting to upgrade to Ember v4.

**Review by sherwinski — APPROVED** [review]
Apologies for the delay there @gilest, everything looks good from where I see it 👍

**Comment by gilest** [comment]
Thanks @sherwinski . Would appreciate a minor release with this patch included 🙇🏻

**Comment by sherwinski** [comment]
@gilest Ah sorry about that, I was expecting semantic release to publish one automatically. I'll get this released for you today.

**Comment by gilest** [comment]
Would still be grateful for a release if that's possible 🙃

**Comment by sherwinski** [comment]
Here you go @gilest - just published [v3.0.3](https://github.com/imgix/ember-cli-imgix/releases/tag/v3.0.3) 🎉 
Thanks for your patience on this!

**Pull request merged**
