### PR TITLE
add support for auto, crop, and fit component attributes

### PR DESCRIPTION
**Pull request by bgentry**
Not sure if this is the direction you want to be going, but I'd love to be able to customize essentially any of the Imgix options as attributes on these components. I added support for `auto`, `crop`, and `fit` here.

### CODE REVIEW

**Comment by bgentry** [comment]
updated to also support the `auto` attribute.

**Comment by kellysutton** [comment]
Awesome! Thanks for the submission. I think this makes a lot of sense. @paulstraw will chime in and merge.

**Comment by paulstraw** [comment]
Looks good to me! I'm going to leave his open until I bump + release a new version.

**Comment by paulstraw** [comment]
Never mind! This is a PR. Ha. Thanks @bgentry.

**Pull request merged**
